### ISSUE TITLE
box-sizing

### ISSUE THREAD

**Issue by tomgp** [Financial-Times/o-normalise#3]
Hi, as it stands the box-sizing property for everything is being set to border-box i.e.   
`* { box-sizing: border-box }` as [the default for this property is specified as `content-box`](https://developer.mozilla.org/en/docs/Web/CSS/box-sizing) this might cause problems if people are expecting the default behaviour. (e.g. [share buttons in our project starter-kit are looking odd](https://github.com/ft-interactive/starter-kit/pull/68#issuecomment-276338125))

**Comment by onishiweb** [comment]
Hmmm ok, this was one of the slight additions to `o-normalise` because we've noticed some issues with `o-grid` usage that breaks when not using `box-sizing: border-box` correctly. I can take this out of non-silent mode styles fairly easily, and if that's being used on a lot of things it might be worthwhile?

**Comment by onishiweb** [comment]
@tomgp I'm going to revert that now and do a minor release (because this is a new component it shouldn't effect anything currently) will this be an ok solution? We'll then look at introducing it in a future major.
