### ISSUE TITLE
.o-normalise-visually-hidden doesn't completely hide o-forms labels

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/o-normalise#30]
Given this html you can see that `o-normalise-visually-hidden` isn’t completely hiding the label. It's only a pixel or 2 but is noticeable.

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.ft.com/__origami/service/build/v2/bundles/css?modules=o-normalise@2.0.0,o-forms@5.9.0" />
</head>

<body>
    <input type="checkbox" class="o-forms__checkbox" name="" id="select"><label for="select" class="o-forms__label o-normalise-visually-hidden">Select</label>
</body>

</html>
```

![screenshot 2018-11-08 10 03 25](https://user-images.githubusercontent.com/11544418/48191674-9eb56b80-e33d-11e8-9bc8-ef80299bd43e.png)

**Comment by notlee** [comment]
Sorry for not getting to this sooner. Thanks for flagging. 👍 I'll take a look when I'm back in the office on Monday (_unless someone beats me to it_).

**Comment by notlee** [comment]
Hey, so the checkbox is made of pseudo elements on the label element. So hiding the label should hide everything, including the checkbox. However because some form styles have higher specificity and override `o-normalise-visually-hidden`, it just so happens to hide only the copy (almost). 😬 

Because the label inself is styled to look like a checkbox, a better approach might be to remove the copy and use `aria-label` on the label element.
```
<input type="checkbox" class="o-forms__checkbox" name="" id="select"><label for="select" class="o-forms__label" aria-label="My hidden checkbox"></label>
```
